### PR TITLE
Add missing HtmlResourceHint valid as-property values according to up…

### PR DESCRIPTION
**Pull request by Munter**
…dated spec

Fixes https://github.com/Munter/subfont/issues/25

### CODE REVIEW

**Comment by Munter** [comment]
I'm not quite sure how this warning could cause subfont to not do it's work. Are we swallowing an exception somewhere?

**Comment by papandreou** [comment]
From the output quoted in https://github.com/Munter/subfont/issues/25 it seems like it did work, it just spewed out those confusing warnings?

**Comment by KyleAMathews** [comment]
We didn't investigate deeper why but can confirm that subfont didn't do any rewriting of the HTML until we'd removed the `<link preload as="fetch">`

**Comment by KyleAMathews** [comment]
Thanks for the quick fix! Launching a new website with this soon! :-D

**Pull request merged**
