### PR TITLE
Ensure all nodeName comparisons are case-insensitive

### PR DESCRIPTION
**Pull request by jscinoz**
Fix for issue #240

### CODE REVIEW

**Comment by papandreou** [comment]
@jscinoz Please look into the failing tests.

**Comment by jscinoz** [comment]
Sorry for the delay, I've been a bit inactive with code outside of work lately. If I get the chance, I'll review the failing test & address the issue this weekend.

**Comment by papandreou** [comment]
Great, looking forward to it :)

**Comment by jscinoz** [comment]
Seems that making the nodeName comparison in the href setter in the HtmlStyle relation was the cause of the test failure. I can't see just what would cause this to be the case, howerver.

**Comment by papandreou** [comment]
Landed in 847c130. Sorry for the delay :)

**Pull request closed without merging**
