### PR TITLE
Model (self-)relations whose href is the empty string or #fragment

### PR DESCRIPTION
**Pull request by papandreou**

### CODE REVIEW

**Comment by Munter** [comment]
This is great. Less special casing, which makes the api more intuitive!

**Comment by papandreou** [comment]
I agree. `_isRelationUrl` used to exclude other things such as`javascript:`, but we model those as well now :)

**Comment by papandreou** [comment]
Okay, pulling it in.

**Comment by Munter** [comment]
I've been testing it against updated hyperlink code during the day. Everything is better with this patch :D

**Comment by papandreou** [comment]
Great to hear that :)

**Pull request merged**
