### PR TITLE
Fixed typos, JS syntax errors

### PR DESCRIPTION
**Pull request by Munawwar**
Added missing open brace.

### CODE REVIEW

**Comment by Munawwar** [comment]
@papandreou K.. I made a mess with the merging etc. You can fix the line manually yourself and close this PR.

**Comment by papandreou** [comment]
Oh, I already merged the other PR and fixed those minor issues :)

**Comment by papandreou** [comment]
The help with es6-ifying is highly appreciated, by the way :). There's still a long way to go. I hope I'll soon have the "simplify addAsset" thing ready so I can "release the lock" on those parts.

**Comment by Munawwar** [comment]
I wonder what if were to run each file through lebab (https://lebab.io/)

**Comment by papandreou** [comment]
Worth the shot :)

**Pull request closed without merging**
