### PR TITLE
Refresh CHANGELOG.md with preversion command

### PR DESCRIPTION
**Pull request by akx**
I noticed the CHANGELOG file hadn't been regenerated with any versions since 6.0.

Maybe a more automated process for this would be nice...

### CODE REVIEW

**Comment by papandreou** [comment]
Hmm, interesting, there's already a `preversion` hook in place for that: https://github.com/assetgraph/assetgraph/blob/e3e25848e0311533b1202c621941a91b153e508f/package.json#L111 🤔

**Comment by papandreou** [comment]
Ah, wait, it's because I'm releasing from the `v7` branch: https://github.com/assetgraph/assetgraph/blob/v7/CHANGELOG.md

It has drifted quite a bit from `master`, so that's why I haven't been merging changes (including `CHANGELOG.md`) back to `master`. Will try to remember that going forward.

**Comment by akx** [comment]
I see. Is there a reason why v7 isn't developed in `master`?

**Comment by papandreou** [comment]
> I see. Is there a reason why v7 isn't developed in `master`?

Yeah, long story. Essentially `master` is being used to develop v8.

**Pull request merged**
