### PR TITLE
Support independent conditional layers

### PR DESCRIPTION
**Pull request by guybedford**
The independent conditions tests aren't passing here, because I think the assetgraph side will need some adjustments to handle the fact that we are now deduping conditional variations by independent bundle layers per condition.

### CODE REVIEW

**Comment by papandreou** [comment]
In [this test](https://github.com/assetgraph/assetgraph/blob/master/test/transforms/bundleSystemJs.js#L765-L786) the output of the bundling strategy is now a nice set of deduped bundles:

```js
{
  bundles: {
    'common-bundle': {
      modules: [ 'main.js', 'weather.js', 'lang.js', 'neededInAllLanguages.js' ],
      source: 'System.registerDynamic(\'lang.js\', [], true, function ($__require, exports, module) {\n  var define,\n      global = this || self,\n      GLOBAL = global;\n  module.exports = Math.random() > .5 ? \'da\' : \'en_us\';\n  return module.exports;\n});\nSystem.registerDynamic(\'main.js\', [\'alert-in-#{weather.js|default}.js\', \'alert-lang-#{lang.js|default}.js\'], true, function ($__require, exports, module) {\n  var define,\n      global = this || self,\n      GLOBAL = global;\n  $__require(\'alert-in-#{weather.js|default}.js\');\n\n  $__require(\'alert-lang-#{lang.js|default}.js\');\n  return module.exports;\n});\nSystem.registerDynamic(\'neededInAllLanguages.js\', [], false, function ($__require, $__exports, $__module) {\n  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal($__module.id, null, null);\n\n  (function ($__global) {\n    alert(\'needed in all languages\');\n  })(this);\n\n  return _retrieveGlobal();\n});\nSystem.registerDynamic(\'weather.js\', [], true, function ($__require, exports, module) {\n  var define,\n      global = this || self,\n      GLOBAL = global;\n  module.exports = Math.random() > .5 ? \'sunny\' : \'rainy\';\n  return module.exports;\n});',
      sourceMap: '{"version":3,"sources":["lang.js","main.js","neededInAllLanguages.js","weather.js"],"names":["module","exports","Math","random","alert"],"mappings":";;;;AAAAA,SAAOC,OAAP,GAAiBC,KAAKC,MAAL,KAAgB,EAAhB,GAAqB,IAArB,GAA4B,OAA7C;;;;;;;ACAA;;AAEA;;;;;;;ACFAC,UAAM,yBAAN;;;;;;;;;ACAAJ,SAAOC,OAAP,GAAiBC,KAAKC,MAAL,KAAgB,EAAhB,GAAqB,OAArB,GAA+B,OAAhD","file":"output.js"}',
      assetList: []
    },
    'bundle-main-rainy': {
      modules: [ 'alert-in-rainy.js' ],
      source: 'System.registerDynamic(\'alert-in-rainy.js\', [], false, function ($__require, $__exports, $__module) {\n  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal($__module.id, null, null);\n\n  (function ($__global) {\n    alert(\'Rainy, yay!\');\n  })(this);\n\n  return _retrieveGlobal();\n});',
      sourceMap: '{"version":3,"sources":["alert-in-rainy.js"],"names":["alert"],"mappings":";;;;AAAAA,UAAM,aAAN","file":"output.js"}',
      assetList: []
    },
    'bundle-main-sunny': {
      modules: [ 'alert-in-sunny.js' ],
      source: 'System.registerDynamic(\'alert-in-sunny.js\', [], false, function ($__require, $__exports, $__module) {\n  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal($__module.id, null, null);\n\n  (function ($__global) {\n    alert(\'Sunny, yay!\');\n  })(this);\n\n  return _retrieveGlobal();\n});',
      sourceMap: '{"version":3,"sources":["alert-in-sunny.js"],"names":["alert"],"mappings":";;;;AAAAA,UAAM,aAAN","file":"output.js"}',
      assetList: []
    },
    'bundle-main-da': {
      modules: [ 'alert-lang-da.js', 'neededInDanish.js' ],
      source: 'System.registerDynamic(\'neededInDanish.js\', [], false, function ($__require, $__exports, $__module) {\n  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal($__module.id, null, null);\n\n  (function ($__global) {\n    alert(\'needed in Danish\');\n  })(this);\n\n  return _retrieveGlobal();\n});\nSystem.registerDynamic(\'alert-lang-da.js\', [\'neededInAllLanguages.js\', \'neededInDanish.js\'], true, function ($__require, exports, module) {\n  var define,\n      global = this || self,\n      GLOBAL = global;\n  $__require(\'neededInAllLanguages.js\');\n\n  $__require(\'neededInDanish.js\');\n\n  alert(\'Danish\');\n  return module.exports;\n});',
      sourceMap: '{"version":3,"sources":["neededInDanish.js","alert-lang-da.js"],"names":["alert"],"mappings":";;;;AAAAA,UAAM,kBAAN;;;;;;;;;ACAA;;AAEA;;AAEAA,QAAM,QAAN","file":"output.js"}',
      assetList: []
    },
    'bundle-main-en_us': {
      modules: [ 'alert-lang-en_us.js', 'neededInAmericanEnglish.js' ],
      source: 'System.registerDynamic(\'neededInAmericanEnglish.js\', [], false, function ($__require, $__exports, $__module) {\n  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal($__module.id, null, null);\n\n  (function ($__global) {\n    alert(\'needed in American English\');\n  })(this);\n\n  return _retrieveGlobal();\n});\nSystem.registerDynamic(\'alert-lang-en_us.js\', [\'neededInAllLanguages.js\', \'neededInAmericanEnglish.js\'], true, function ($__require, exports, module) {\n  var define,\n      global = this || self,\n      GLOBAL = global;\n  $__require(\'neededInAllLanguages.js\');\n\n  $__require(\'neededInAmericanEnglish.js\');\n\n  alert(\'American English\');\n  return module.exports;\n});',
      sourceMap: '{"version":3,"sources":["neededInAmericanEnglish.js","alert-lang-en_us.js"],"names":["alert"],"mappings":";;;;AAAAA,UAAM,4BAAN;;;;;;;;;ACAA;;AAEA;;AAEAA,QAAM,kBAAN","file":"output.js"}',
      assetList: []
    }
  },
  entryPointBundles: [
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: { 'lang.js|default': 'da', 'weather.js|default': 'rainy' },
      bundles: [ 'common-bundle', 'bundle-main-rainy', 'bundle-main-da' ]
    },
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: { 'lang.js|default': 'da', 'weather.js|default': 'sunny' },
      bundles: [ 'common-bundle', 'bundle-main-sunny', 'bundle-main-da' ]
    },
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: { 'lang.js|default': 'en_us', 'weather.js|default': 'rainy' },
      bundles: [ 'common-bundle', 'bundle-main-rainy', 'bundle-main-en_us' ]
    },
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: { 'lang.js|default': 'en_us', 'weather.js|default': 'sunny' },
      bundles: [ 'common-bundle', 'bundle-main-sunny', 'bundle-main-en_us' ]
    }
  ]
}
```

Right now it doesn't seem to be possible to tell from the `entryPointBundles` section exactly which condition values caused which bundles to be defined? Would it be possible to output something like the below?

```js
  entryPointBundles: [
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: {},
      bundles: [ 'common-bundle' ]
    },
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: { 'lang.js|default': 'da' },
      bundles: [ 'bundle-main-da' ]
    },
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: { 'lang.js|default': 'en_us' },
      bundles: [ 'bundle-main-en_us' ]
    },
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: { 'weather.js|default': 'sunny' },
      bundles: [ 'bundle-main-sunny' ]
    },
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: { 'weather.js|default': 'rainy' },
      bundles: [ 'bundle-main-rainy' ]
    }
  ]
```

... if that makes sense?

**Comment by papandreou** [comment]
@guybedford I updated the tests now. They should pass if the `entryPointBundles` format is changed like I suggest above :)

**Comment by guybedford** [comment]
Just saw this now - I seemed to have missed these comments somehow.

We currently dedupe bundles against eachother so that the same bundle can be used in different places if the modules match. Strictly speaking, while each bundle does have a unique generation entry point and conditional etc, because of this deduping it wouldn't be correct to say that a bundle is only generated from a given condition.

Given a conditional object, it is possible to trace which bundles would apply by iterating entryPointBundles and finding the right matches. Does that not cover the need here?

**Comment by papandreou** [comment]
Oh, okay, I should have known that I was missing something :)

> Given a conditional object, it is possible to trace which bundles would apply by iterating entryPointBundles and finding the right matches. Does that not cover the need here?

Hmm, maybe. Basically for each entry point I need to generate markup like this from the result of the bundle strategy:

```html
<script src=... data-assetgraph-conditions="weather: 'sunny'"></script>
<script src=... data-assetgraph-conditions="weather: 'rainy'"></script>
<script src=... data-assetgraph-conditions="favoriteColor: 'blue'"></script>
<script src=... data-assetgraph-conditions="favoriteColor: 'beige'"></script>
<!-- and when conditions turn out to be dependent there would be no way to avoid: -->
<script src=... data-assetgraph-conditions="foo: 'first', bar: 'abc'"></script>
<script src=... data-assetgraph-conditions="foo: 'last', bar: 'abc'"></script>
<script src=... data-assetgraph-conditions="foo: 'first', bar: 'xyz'"></script>
<script src=... data-assetgraph-conditions="foo: 'last', bar: 'xyz'"></script>
<script src=common-bundle.js></script>
```

... where the idea is that there should be as few of these scripts as possible, especially when the conditions are independent, secondarily with as little duplication/total weight as possible.

At least that is what I envisioned, so I would of course prefer that the output of the bundle strategy is as close to this as possible.

Your suggestion is to do another round of tracing/querying based on the output of the current bundle strategy? Could you show a rough example of what that would look like, and what the result would be?

**Comment by guybedford** [comment]
What if we flip this then rather and list bundles by entry point + conditional:

```javascript
{
  bundles: {
    'common-bundle': {
      entryPoints: [{
        name: 'main.js',
        deferredParent: undefined,
        conditions: {}
      }],
      modules: [ 'main.js', 'weather.js', 'lang.js', 'neededInAllLanguages.js' ],
      source: 'System.registerDynamic(\'lang.js\', [], true, function ($__require, exports, module) {\n  var define,\n      global = this || self,\n      GLOBAL = global;\n  module.exports = Math.random() > .5 ? \'da\' : \'en_us\';\n  return module.exports;\n});\nSystem.registerDynamic(\'main.js\', [\'alert-in-#{weather.js|default}.js\', \'alert-lang-#{lang.js|default}.js\'], true, function ($__require, exports, module) {\n  var define,\n      global = this || self,\n      GLOBAL = global;\n  $__require(\'alert-in-#{weather.js|default}.js\');\n\n  $__require(\'alert-lang-#{lang.js|default}.js\');\n  return module.exports;\n});\nSystem.registerDynamic(\'neededInAllLanguages.js\', [], false, function ($__require, $__exports, $__module) {\n  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal($__module.id, null, null);\n\n  (function ($__global) {\n    alert(\'needed in all languages\');\n  })(this);\n\n  return _retrieveGlobal();\n});\nSystem.registerDynamic(\'weather.js\', [], true, function ($__require, exports, module) {\n  var define,\n      global = this || self,\n      GLOBAL = global;\n  module.exports = Math.random() > .5 ? \'sunny\' : \'rainy\';\n  return module.exports;\n});',
      sourceMap: '{"version":3,"sources":["lang.js","main.js","neededInAllLanguages.js","weather.js"],"names":["module","exports","Math","random","alert"],"mappings":";;;;AAAAA,SAAOC,OAAP,GAAiBC,KAAKC,MAAL,KAAgB,EAAhB,GAAqB,IAArB,GAA4B,OAA7C;;;;;;;ACAA;;AAEA;;;;;;;ACFAC,UAAM,yBAAN;;;;;;;;;ACAAJ,SAAOC,OAAP,GAAiBC,KAAKC,MAAL,KAAgB,EAAhB,GAAqB,OAArB,GAA+B,OAAhD","file":"output.js"}',
      assetList: []
    },
    'bundle-main-rainy': {
      entryPoints: [{
        name: 'main.js',
        deferredParent: undefined,
        conditions: { 'lang.js|default': 'da' }
      }],
      modules: [ 'alert-in-rainy.js' ],
      source: 'System.registerDynamic(\'alert-in-rainy.js\', [], false, function ($__require, $__exports, $__module) {\n  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal($__module.id, null, null);\n\n  (function ($__global) {\n    alert(\'Rainy, yay!\');\n  })(this);\n\n  return _retrieveGlobal();\n});',
      sourceMap: '{"version":3,"sources":["alert-in-rainy.js"],"names":["alert"],"mappings":";;;;AAAAA,UAAM,aAAN","file":"output.js"}',
      assetList: []
    },
    'bundle-main-sunny': {

      modules: [ 'alert-in-sunny.js' ],
      source: 'System.registerDynamic(\'alert-in-sunny.js\', [], false, function ($__require, $__exports, $__module) {\n  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal($__module.id, null, null);\n\n  (function ($__global) {\n    alert(\'Sunny, yay!\');\n  })(this);\n\n  return _retrieveGlobal();\n});',
      sourceMap: '{"version":3,"sources":["alert-in-sunny.js"],"names":["alert"],"mappings":";;;;AAAAA,UAAM,aAAN","file":"output.js"}',
      assetList: []
    },
    'bundle-main-da': {
      modules: [ 'alert-lang-da.js', 'neededInDanish.js' ],
      source: 'System.registerDynamic(\'neededInDanish.js\', [], false, function ($__require, $__exports, $__module) {\n  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal($__module.id, null, null);\n\n  (function ($__global) {\n    alert(\'needed in Danish\');\n  })(this);\n\n  return _retrieveGlobal();\n});\nSystem.registerDynamic(\'alert-lang-da.js\', [\'neededInAllLanguages.js\', \'neededInDanish.js\'], true, function ($__require, exports, module) {\n  var define,\n      global = this || self,\n      GLOBAL = global;\n  $__require(\'neededInAllLanguages.js\');\n\n  $__require(\'neededInDanish.js\');\n\n  alert(\'Danish\');\n  return module.exports;\n});',
      sourceMap: '{"version":3,"sources":["neededInDanish.js","alert-lang-da.js"],"names":["alert"],"mappings":";;;;AAAAA,UAAM,kBAAN;;;;;;;;;ACAA;;AAEA;;AAEAA,QAAM,QAAN","file":"output.js"}',
      assetList: []
    },
    'bundle-main-en_us': {
      modules: [ 'alert-lang-en_us.js', 'neededInAmericanEnglish.js' ],
      source: 'System.registerDynamic(\'neededInAmericanEnglish.js\', [], false, function ($__require, $__exports, $__module) {\n  var _retrieveGlobal = System.get("@@global-helpers").prepareGlobal($__module.id, null, null);\n\n  (function ($__global) {\n    alert(\'needed in American English\');\n  })(this);\n\n  return _retrieveGlobal();\n});\nSystem.registerDynamic(\'alert-lang-en_us.js\', [\'neededInAllLanguages.js\', \'neededInAmericanEnglish.js\'], true, function ($__require, exports, module) {\n  var define,\n      global = this || self,\n      GLOBAL = global;\n  $__require(\'neededInAllLanguages.js\');\n\n  $__require(\'neededInAmericanEnglish.js\');\n\n  alert(\'American English\');\n  return module.exports;\n});',
      sourceMap: '{"version":3,"sources":["neededInAmericanEnglish.js","alert-lang-en_us.js"],"names":["alert"],"mappings":";;;;AAAAA,UAAM,4BAAN;;;;;;;;;ACAA;;AAEA;;AAEAA,QAAM,kBAAN","file":"output.js"}',
      assetList: []
    }
  },
  entryPointBundles: [
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: { 'lang.js|default': 'da', 'weather.js|default': 'rainy' },
      bundles: [ 'common-bundle', 'bundle-main-rainy', 'bundle-main-da' ]
    },
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: { 'lang.js|default': 'da', 'weather.js|default': 'sunny' },
      bundles: [ 'common-bundle', 'bundle-main-sunny', 'bundle-main-da' ]
    },
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: { 'lang.js|default': 'en_us', 'weather.js|default': 'rainy' },
      bundles: [ 'common-bundle', 'bundle-main-rainy', 'bundle-main-en_us' ]
    },
    {
      name: 'main.js',
      deferredParent: undefined,
      conditions: { 'lang.js|default': 'en_us', 'weather.js|default': 'sunny' },
      bundles: [ 'common-bundle', 'bundle-main-sunny', 'bundle-main-en_us' ]
    }
  ]
}
```

**Comment by papandreou** [comment]
That would work great for me!

**Comment by papandreou** [comment]
I changed the rest of `bundleSystemJs` to expect the new proposed result object from the bundle strategy.

**Comment by guybedford** [comment]
I've made a first attempt at this output update. It still isn't deduping the entryPoints by condition though, which would need to be another step added I think?

**Comment by guybedford** [comment]
I've updated the PR with deduplication, tests should be passing now :)

**Comment by papandreou** [comment]
This looks very promising! I am able to build multi-page apps now. It's still somewhat slow, but it doesn't seem to be due to `bundleSystemJs` anymore, so I'll be looking into that :)

When I try to build two pages  in my app at once, and one of them is that page that only utilizes the less plugin, I get a crash in https://github.com/assetgraph/assetgraph/blob/feature/independent-conditional-layering/lib/transforms/bundleSystemJs.js#L534

```
 ✘ ERROR: TypeError: buildProduction transform: bundleSystemJs transform: Cannot read property 'entryPoints' of undefined
              at /home/andreas/work/assetgraph/lib/transforms/bundleSystemJs.js:534:42
              at Array.forEach (native)
              at /home/andreas/work/assetgraph/lib/transforms/bundleSystemJs.js:475:27
              at tryCatcher (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/util.js:16:23)
              at Promise._settlePromiseFromHandler (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:510:31)
              at Promise._settlePromise (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:567:18)
              at Promise._settlePromise0 (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:612:10)
              at Promise._settlePromises (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:691:18)
              at Promise._fulfill (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:636:18)
              at PromiseArray._resolve (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise_array.js:125:19)
              at PromiseArray._promiseFulfilled (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise_array.js:143:14)
              at Promise._settlePromise (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:572:26)
              at Promise._settlePromise0 (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:612:10)
              at Promise._settlePromises (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:691:18)
              at Promise._fulfill (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:636:18)
              at Promise._resolveCallback (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:431:57)
              at Promise._settlePromiseFromHandler (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:522:17)
              at Promise._settlePromise (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:567:18)
              at Promise._settlePromise0 (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:612:10)
              at Promise._settlePromises (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:691:18)
              at Promise._fulfill (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:636:18)
              at Promise._resolveCallback (/home/andreas/work/assetgraph/node_modules/bluebird/js/release/promise.js:431:57)
```

does that make sense?

**Comment by papandreou** [comment]
I reduced it to a simpler test case -- pushed. Apparently it depends on the two entry points not sharing a single module -- if I add `dep.js` and require it from both `main1.js` and `main2.js`, it doesn't fail.

**Comment by papandreou** [comment]
Thanks a lot -- I fixed the lint problems.

**Comment by papandreou** [comment]
Let's roll :)

**Comment by guybedford** [comment]
🎉

**Pull request merged**
