### PR TITLE
chore: add Node.js 10

### PR DESCRIPTION
**Pull request by DanielRuf**
And for testing what will fail and fix the issues to get it working on Node.js 10.

### CODE REVIEW

**Comment by papandreou** [comment]
Thanks! Good to get on track with this. I also [tried this previously](https://github.com/assetgraph/assetgraph/commit/61a9c92fdd3f08b04c1dea4e049e14b18c5f2705) without much luck.

Seems like it's running into a problem with the http mocking library we use. I talked to @alexjeffburke earlier today, he was trying to fix it, but it didn't exactly seem trivial. We'll get there :)

**Comment by DanielRuf** [comment]
I'll check if and how we can get a working solution.

**Comment by papandreou** [comment]
@DanielRuf, thanks! My hunch is that it's an compatibility issue with [node-mitm](https://github.com/moll/node-mitm/) and node.js 10. I previously [fixed it for node 9.6.0](https://github.com/moll/node-mitm/issues/48), but the node guys are reshuffling a lot of internals.

Would be good to hear if Alex has made progress so we don't duplicate the effort, though.

**Comment by alexjeffburke** [comment]
Thanks for the headsup :) Yeah it seems to be something fundamental inside node-mitm - what seems to happen is a `request` event never comes up through the mitm() instance.

I’ll add a couple more notes - it felt like it was due to timing changes due to other things that have happened in node. I tried to hack around that and I also tried to directly wrap the base socket class connect method rather than the routes into it (mitm tries to intercept createConnection in the 3 or so places it exists). After a good few hours spent today it seems rather hairy - feel free to give it a go.. I’d only ask that we share findings as I think this will be a the more minds the better type situation :)

**Comment by DanielRuf** [comment]
Mh, seems so. I do not get any valid response object at all.

**Comment by alexjeffburke** [comment]
@danielruf yep unfortunately that’s the symptom :/ It’s very late though so will leave you with a good luck If I chip away any more in the morning and get anywhere will mention it here.

**Comment by papandreou** [comment]
In case you're still on this, I found [the commit](https://github.com/nodejs/node/commit/e85c20b511544ee66e22b80916a9666a55c5aedb) where this started breaking:

```
e85c20b511544ee66e22b80916a9666a55c5aedb is the first bad commit
commit e85c20b511544ee66e22b80916a9666a55c5aedb
Author: Anna Henningsen <anna@addaleax.net>
Date:   Sun Apr 1 20:56:11 2018 +0200

    net,http2: merge write error handling & property names
    
    Merge error handling for `net.Socket`s and `Http2Stream`s,
    and align the callback property names as `callback`.
    
    Refs: https://github.com/nodejs/node/issues/19060
    
    PR-URL: https://github.com/nodejs/node/pull/19734
    Reviewed-By: Luigi Pinca <luigipinca@gmail.com>
    Reviewed-By: Tobias Nießen <tniessen@tnie.de>
    Reviewed-By: James M Snell <jasnell@gmail.com>
    Reviewed-By: Matteo Collina <matteo.collina@gmail.com>
    Reviewed-By: Trivikram Kamat <trivikr.dev@gmail.com>

:040000 040000 0d7a8825060ce8753b6f805d3cd73bada9b20fe6 f81b25cbe65242fc5ad1433988d319c6e3d3bbfb M	lib
```

**Comment by DanielRuf** [comment]
Did you find this with `git bisect`?

**Comment by alexjeffburke** [comment]
Hmm interesting, thanks for doing this - I’m still chipping away, I had a version that actually passed the client read/write tests and close events but I just can’t seem to get the fabricated http server (created via _connectionListener) to emit the request event correctly - let me see if this big new puzzle piece helps.

**Pull request merged**
