### PR TITLE
Make relations owned by the asset containing them

### PR DESCRIPTION
**Pull request by papandreou**
This needs some more polish, but shows the general idea. ag-b tests don't pass yet.

Preserves the `findRelations` API (for now).

CC: @Munter

### CODE REVIEW

**Comment by Munter** [comment]
Yay! This looks really good

**Comment by papandreou** [comment]
Thanks! I'll try to finish it up ASAP.

It unlocks a bunch of interesting things that we might want to explore right away:

1) New query syntax -- something jquery-ish with the transform pipeline built-in?
2) Something like `markDirty` that also invalidates the relations so they're re-discovered on demand? (We talked about this on the gitter channel about a month ago)
3) Instantiate `Asset` objects right away instead of keeping "asset configs" around, then subclass when the metadata (especially the type) is known. Could clear up a lot of inconsistencies.

**Comment by Munter** [comment]
Those are big wins I think. Will make the behaviour less surprising

**Comment by papandreou** [comment]
Seems like this works now.

Sister PRs:
https://github.com/assetgraph/assetgraph-builder/pull/517
https://github.com/assetgraph/assetgraph-sprite/pull/140

**Pull request merged**
