### PR TITLE
Include list indicators in subset

### PR DESCRIPTION
**Pull request by papandreou**
- [x] Disregard `symbols: url(gold-medal.svg) url(silver-medal.svg) url(bronze-medal.svg);` in `@counter-style` rules.
- [x] Support additional properties `@counter-style foo { pad: 'something'; additive-symbols: ... }`
- [x] Separate `content` values from `text` again. Now that the `content` support is quite advanced, it no longer makes sense to shoehorn `node.textContent` into it.

### CODE REVIEW

**Comment by papandreou** [comment]
Still missing support for:

```css
@counter-style custom-emoji {
  system: cyclic;
  symbols: 😀 😍 😝 😱
  suffix: " ";
}
```

```css
.foo::after {
  content: counter(chapter_counter);
}
```

```css
.foo::after {
  content: counters(section_counter, ".");
}
```

**Comment by papandreou** [comment]
Also, there are some more markers here: https://meyerweb.com/eric/css/tests/css2/sec12-06-02a.htm

**Comment by papandreou** [comment]
@Munter, I believe this is ready now :)

**Comment by Munter** [comment]
Wow :O 

Let's get it in! 🎊

**Comment by papandreou** [comment]
Released 3.9.0 with it and merged v3 to master (much easier this time :)

**Pull request merged**
