### PR TITLE
Trace ::first-letter and ::first-line when subsetting fonts

### PR DESCRIPTION
**Pull request by papandreou**
This is a bit of a mess, I know. Tracing those required a restructuring of how text and pseudo elements are traced.

Bonus feature: `::placeholder`

### CODE REVIEW

**Comment by papandreou** [comment]
The reordering happened as a result of tracing the node, pseudo elements, and children in a slightly different order. It's a bit intricate because of the counter adjustments etc. I was careful to check that the same entries were there in all the affected tests.

Might be possible to get it back to the previous state with a bit of work.

**Comment by Munter** [comment]
The order doesn't matter in our later processing, so I don't care much. I was just wondering :)

**Comment by Munter** [comment]
Now we just need to figure out how to port this to v4 :)

**Comment by papandreou** [comment]
:+1:

It should merge cleanly to master. I've deliberately not touched `{test,lib}/util/fonts/getTextByFontProperties.js` there because this was still open.

**Pull request merged**
